exp_name: "2025_0114_030455_s2"
model_path:  /home/tmy/Desktop/adaptive-patch-size-dark-channel-prior/results/RESIDE-6K/model/2025_0114_030455_s2/model_final.pth
save_dir: /home/tmy/Desktop/adaptive-patch-size-dark-channel-prior/results/RESIDE-6K/result

dataset:
  name: RESIDE-6K
  data_dir: /home/tmy/Desktop/RESIDE-6K/test/hazy
  max_size: 0
  padding_mul: 8
  num_workers: 8
