exp_name: "two_stage"
model_path:  ckpts/apsdcp-net-ckpt.pth
save_dir: results/RESIDE-6K/result

dataset:
  name: RESIDE-6K
  data_dir: /home/tmy/Desktop/RESIDE-6K/test/hazy
  max_size: 0
  padding_mul: 8
  num_workers: 8
