exp_name: "second_stage"
save_dir: results/RESIDE-6K
stage1_path: /path/to/first/stage/model/  # change this to the actual path of the first stage model

dataset:
  name: RESIDE-6K
  data_dir: /home/tmy/Desktop/RESIDE-6K  # change this to your dataset path
  batch_size: 8
  crop_size: 256
  max_size: 0
  padding_mul: 8
  num_workers: 8

lr: !!float 2e-4
max_iter: 500000
warmup_iter: 5000
eval_freq: 5000

note: ""
