exp_name: "first_stage"
save_dir: results/RESIDE-6K

dataset:
  name: RESIDE-6K
  data_dir: /home/tmy/Desktop/RESIDE-6K  # change this to your dataset path
  batch_size: 16
  crop_size: 256
  max_size: 0
  padding_mul: 8
  num_workers: 8

lr: !!float 2e-4
max_iter: 200000
fix_pss_iter: 200000
warmup_iter: 3000
eval_freq: 5000

note: ""
